language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Ld9lv0HihxT4j9DAb7NdSoiZF49MAY4xZzI3PwKw6naNw/BVWlXacpT48RNkSbaDjHy9/O/I8KQfO6BEohx47yKtfKOgQATvWhi0gFbEc06z2TxOMRW3VWf7kGONTD7WccN8UkJp7h27d26ohSPaGL3LClfznUoXRuxkO4VBY7NxYDXUnOdoRMGhU0ENjCRRHcpBKve3/LFu/ehF/kvxGTK35ZtMqc1AEYuMyJ7IzeKpr03xInJgwmEcoY6R1bjLgvkqsfnDVGavf4RfcGFqaUBMGoa2MWW71UZuuO5P0bcCrOGlylsSptyux3+TK4Ocbu5wVi9bcH/xNbzb+BQFjvKbacayfb4hsLe95+LdzLZo7kNgpAulFsclp3Rtmv+Jvmt10XLnG9d6xtTlRkojgptvpbGnbE73lzo3d7WFotWumcMLVyrWP7Vx0sxNtEHD9cCNcghD7LIVIWRnPCcA4u4Q9LpZeRF/DpClojdO7oZH2OHYNdeG87bAho1wShyRDOL8XYL6VeSE5Y9p6ldVKj94RuGQ0+zNdfNPVSBHeHVbyM+oOubPxdwgkuITGob6/EagG0V1O7505PytTF+Sch0vRe+DlJFP8fxoIAXYHxJaKbSb60IXmLOPLbh9+nJaCa0+XBa2OZrB/MvvSLCLmuHiAgRDIcLLZSRp0Psr4DA=
  app: have-another
  on:
    repo: Btan579/HaveAnother
