language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: m/SfBIw9Mv/uQjPSwMGheArLcXGk/ieFbOwCZ1S9MMfnpbQ2JYvmFrUIJwdZNs0RcnHbAsIYMtTYpftTjkv9jKpLsivtR7KBWEuM1iTIKiOMgUu2nYJwUwzVL+ZfkSShmIue4m8dINScaHnpuVMWNvHhlricpP7ejQ9M9Rz6C3wluRNbZ68yMfhmByTs8LLJj9dgXDHJY70qD60hmVkmzZw7NXqQB9H4HJcSpQKo8+llmXZ6vLu28cvanXZWELa/wGbZDCs8++vieS+xHoMcr7aDIaH5BUpSlRCmmVpu7olXCVW46ryOHpmfTC1VlAlbVMfSzYrtUeJQd8BW3/iVSgQggOG4Se5ZV1ej1+S1ws1q8z7j6/dYfbbqkLH2zVqQZTHspsFWj2kK20JIGWSLAcXvK5dZeTTW4VdNLYNOOHTa96oTOw9u9wmERU6ehwWdO9X0X2IzmzFlqIz05N+qoy2f0R+aYz9XGabR2U7fRgToKp0SRnG8Zja56EI+eAEVCv020aPxH/6SyvwHcMTn7DWuVMUuA19EoaNSTZp+Vsn30rT5wWfa/y9dtyx9VahimxIZMjViUkrFolDX/YC7FLCcdhPbLEmc6eaCd4Zb2gnilcmukdpRCtevI8lbPXXFGgD3rwj1Q6w43iTxoTgTWAbjPUKoaPJVfn22+XqpHBk=
  app: have-another
  on:
    repo: Btan579/HaveAnother
